# Generated by Django 4.2 on 2024-07-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
