# Generated by Django 4.2 on 2024-07-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_comment_post_alter_post_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="ip",
            field=models.GenericIPAddressField(null=True),
        ),
    ]
