# Generated by Django 4.2 on 2024-07-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_post_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
